export const routeNames = {
  login: "/",
  dashboard: "/dashboard",
  orders: "/orders",
  products:( ProductId)=>`/products/${ProductId}`,
  brands:( BrandID)=>`/brands/${BrandID}`,
  allProducts: "/all-products",
  customers: "/customers",
  reports: "/reports",
  settings: "/settings",
  newproducts:"/products",
  categories:( categoryID)=>`/categories/${categoryID}`,
  newCategory:"/categories/new",
  newBrands:"/brands/new",
  Browse:"/Browse",
  Productcreation:"/Browse/product",
  step1: "/Browse/step1",
  step2: "/Browse/step2",
  step3: "/Browse/step3",
  editCategory:(categoryID)=>`/Browse/step2/editCategory/${categoryID}`,
  editProductType:( ProductTypeID)=>`/Browse/step3/editProductType/${ProductTypeID}`,
  editCreateBrand:(BrandID)=>`/Browse/step1/editCreateBrand/${BrandID}`,
  editCreateColor:(ColourID)=>`/Browse/step4/editCreateColor/${ColourID}`,
  editCreateSize:(SizeID)=>`/Browse/step5/editCreateSize/${SizeID}`,
  step4: "/Browse/step4",
  step5: "/Browse/step5",
};
 